server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/toys/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/pay/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/